# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{howdy}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["mlomnicki"]
  s.date = %q{2010-03-12}
  s.default_executable = %q{how}
  s.description = %q{Howdy is a tool that allows querying web dictionaries from a command line.}
  s.email = %q{michal.lomnicki@gmail.com}
  s.executables = ["how"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/how",
     "howdy.gemspec",
     "lib/howdy.rb",
     "lib/howdy/base.rb",
     "lib/howdy/config.rb",
     "lib/howdy/core_ext/ruby/string/integer.rb",
     "lib/howdy/core_ext/ruby/string/underscore.rb",
     "lib/howdy/dictionaries/dict_pl.rb",
     "lib/howdy/dictionaries/dictionary_com.rb",
     "lib/howdy/dictionaries/ling_pl.rb",
     "lib/howdy/dictionaries/urban_dictionary_com.rb",
     "lib/howdy/templates/howdy",
     "lib/howdy/ui.rb",
     "spec/howdy_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mlomnicki/howdy}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Query web dictionaries from command line}
  s.test_files = [
    "spec/howdy_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

